# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Теория языков программирования на ФКН
site_url: https://church-of-church-hse.github.io
nav:
  - Главная: index.md
  - Проекты:
    - projects/index.md
    - projects/catcomp.md
    - projects/codeaswiki.md
    - projects/dependobuf.md
    - projects/gc.md
    - projects/graphcat.md
    - projects/hitgc.md
    - projects/mlgc.md
    - projects/parsergen.md
    - projects/sanskrit.md
    - projects/shaderdsl.md
    - projects/twelf.md
    - projects/zksnark.md
  - testtask.md
theme:
  name: material
  language: ru
  features:
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Системная тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Светлая тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Тёмная тема
plugins:
  - search
  - social
  - tags:
      tags_file: index.md
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Church-of-Church-HSE/
  tags:
    КР 24/25: cw24
    ВКР 24/25: bw24
    Проект 24/25: pr24
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
